import { UserRole, RoleConfig, UserProfile } from '../types/auth';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  patient: {
    role: 'patient',
    title: 'Patient Portal',
    subtitle: 'Sign in to access your consultations, health records & medical appointments',
    iconName: 'person-outline',
    identifierLabel: 'Email or Mobile Number',
    identifierPlaceholder: 'name@domain.com or 10-digit number',
    identifierRightActionText: 'UHID / Patient ID',
    defaultEmailOrId: 'rahul.verma@example.com',
    demoPassword: '••••••••••••',
    portalName: 'Patient Health Dashboard',
    primaryColor: '#0080FF',
    badgeText: 'Verified Patient',
  },
  doctor: {
    role: 'doctor',
    title: 'Doctor OPD Portal',
    subtitle: 'Sign in to manage your OPD queues, clinic schedules & consultations',
    iconName: 'medkit-outline',
    identifierLabel: 'Doctor ID or Mobile Number',
    identifierPlaceholder: 'dr.name@domain.com or NMC / Reg No',
    identifierRightActionText: 'NMC / Reg No',
    defaultEmailOrId: 'dr.rajesh@upcharhealth.in',
    demoPassword: '••••••••••••',
    portalName: 'Doctor OPD & Clinics',
    primaryColor: '#0284C7',
    badgeText: 'NMC Verified Doctor',
  },
  lab: {
    role: 'lab',
    title: 'Diagnostic & Lab Portal',
    subtitle: 'Sign in to manage diagnostic orders, sample collections & test reports',
    iconName: 'flask-outline',
    identifierLabel: 'Lab Code or Admin Email',
    identifierPlaceholder: 'lab@domain.com or Lab License ID',
    identifierRightActionText: 'Diagnostic Reg ID',
    defaultEmailOrId: 'apex.pathology@upcharhealth.in',
    demoPassword: '••••••••••••',
    portalName: 'Diagnostic Sample & Report Hub',
    primaryColor: '#0D9488',
    badgeText: 'NABL Accredited Lab',
  },
};

export const DEMO_USERS: Record<UserRole, UserProfile> = {
  patient: {
    id: 'pat-1001',
    name: 'Rahul Verma',
    role: 'patient',
    identifier: 'UPC-PAT-882910',
    email: 'rahul.verma@example.com',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'UHID: UPC-882910 • Blood Group O+',
    isVerified: true,
  },
  doctor: {
    id: 'doc-2001',
    name: 'Dr. Rajesh Sharma',
    role: 'doctor',
    identifier: 'MCI-REG-44921',
    email: 'dr.rajesh@upcharhealth.in',
    phone: '+91 94321 09876',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'MD, General Medicine • 12+ Yrs Exp',
    isVerified: true,
  },
  lab: {
    id: 'lab-3001',
    name: 'Apex Diagnostic & Pathology Hub',
    role: 'lab',
    identifier: 'DX-NABL-77291',
    email: 'apex.pathology@upcharhealth.in',
    phone: '+91 98223 11445',
    avatarUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'NABL Accredited • Pathology & Radiology',
    isVerified: true,
  },
};
